url: "https://www.fortressoflies.com" # Should not end with /
username: "Zugbot"

game_name: "Refactored Test"
game_start_time: '' # If not '', then the game will start at this time. Also, all phases
    # will have start and end times calculated off of this time. This is in 24 hour time. This should be in the timezone
    # specified in utc_offset.
    # Example format: "2024-08-13 08:00"
utc_offset: "-04:00"

host_usernames:
- Zugzwang
- Zwischenzug
playerlist_usernames:
- Zug
- zug_alt_1
- zug_alt_2
- NotAZug
- NotAZugAlt
- zug_alt_account
- secret_cookie_thread
- Eigenzug
- Eigenalt
- Unzug
- Zqgzwqng
- AlsoZug
topic_id: 9145 # The topic ID of the game thread

mafia_discord_link: ''
rand_roles: true # Whether to rand roles. Set to true in games! This option is here for easier debugging.

day_length: 60 # In minutes
night_length: 10 # In minutes
action_deadline: 1 # Actions can no longer be submitted this many minutes before phase change. Should be at least 1.

setup_name: 'fam6' # Must exactly match the name in the setups folder

include_itas: true # If true, ITA windows will exist.
ita_windows: # Each number represents the number of minutes past SOD.
    - start: 1
      end: 20
    - start: 30
      end: 40
ita_base_damage: 10 # The base damage of ITAs
ita_ads: false # Whether to have 'ads' in ITAs.

do_not_flip: true # Disables flips (and also disables Zugbot's game end check, so that Zugbot never ends the game on its own)
allow_closing_and_opening_threads: true
disable_day_and_night_start_announcements: true

# Most users can safely ignore everything below this line.

send_messages_to_hosting_discord: true # True if debug messages should be sent to a host discord
hosting_discord_channel_id_for_output: 1503775486889820282 # The ID of the discord channel to output debug messages to
hosting_discord_guild_id: 1462965682970038305 # Most commands are only visible in this discord

resolve_like_vc_plugin: true # Should be set to true for most use cases.

turbo_pm_json_path: "turbo_pms.json" # ignored if not running turbos. For turbos, this provides topic IDs for previous PMs
                                     # used to speed up role distribution.

action_processor_sleep_seconds: 5 # Time slept between consecutive checks for new action submissions (in seconds)
                                  # This has a large impact on rate limiting issues.

delay_between_post_checks: 1 # Time slept between checks of the posting queue (in seconds)
delay_between_posts: 2 # Minimum delay between posts Zugbot makes (in seconds)

exception_retry_delay: 5 # Time to wait to retry an API call if an exception occurs (in seconds)
max_exception_retries: 20 # Maximum number of times to retry an API call before giving up

restore_delay_minutes: 5 # Every restore_delay_minutes, the game is saved.
min_delay_between_saves_seconds: 30 # Saves are cancelled if there has been a save in the last min_delay_between_saves_seconds.

vc_post_cooldown: 10 # The minimum delay (in seconds) between votecount posts (including ones requested by /votecount)
votecount_time_interval: 120 # The number of minutes between automatic votecount posts (not requested by /votecount)
votecount_post_interval: 10 # The number of posts between automatic votecount posts (not requested by /votecount)


debug_print_all_posts: true

crash_on_exception: true # Makes Zugbot crash entirely when reaching an unhandeled exception. Also, inadvertently turns off restore saving.